Feature milestone 1
nurislam-ab/calculator_react pull request #1
Opened 2020-10-12 16:47 UTC by nurislam-ab

This PR has the following:
[x] React setup
[x] Linters setup
[x] Heroku deploy

2020-10-12 18:08 UTC, Torres-ssf requested changes
### Changes required :muscle: 
Hi @nurislam-ab :hand: 
Awesome job in this milestone :clap: 
But we need to make some changes before moving on.

- [x] We need to improve the README file by adding relevant information about your project. This requirement is listed on Microverse General Requirements. You can use this template [here](https://github.com/microverseinc/readme-template). Remember to also inform the link from the live version of your application.
![Screenshot from 2020-10-12 15-00-18](https://user-images.githubusercontent.com/30977845/95776966-ac976800-0c9b-11eb-953a-c44c596f0c17.png)

- [x] Awesome job cleaning your project and deleting the unnecessary files. However, there was no need to delete index.js and app.js. Instead of that what can be done in the setup stages is to make the App component to return only a simple message (like `Hello World`) on an `h1` or `p` element.

Feel free to message me on slack if you have any questions :smile: 
Happy Coding :computer: 
**Sergio Torres**

2020-10-12 18:08 UTC, Torres-ssf commented on .github/workflows/linters.yml
> +        run: npx eslint .
- [ ] This file was updated 2 weeks ago. We need to use to the most recent one. You can find it [here](https://github.com/microverseinc/linters-config/blob/master/react-redux/.github/workflows/linters.yml):

2020-10-13 08:52 UTC, mikenath223 approved these changes
### Hi @nurislam-ab 👋

**Nice work so far on this. 👍**

### STATUS: REQUESTED CHANGES 👷‍♂️

- [x] - OPTIONAL - Please consider changing the files extension of the files in the directory of `src/components` from `jsx` to simply `js`.

- [ ] - OPTIONAL - Is there a reason why your Github actions run twice for each lint action? Kindly consider fixing it.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-10-13 09:13 UTC, nurislam-ab commented
> * [ ]  - OPTIONAL - Is there a reason why your Github actions run twice for each lint action? Kindly consider fixing it.

Tried to find the reason but was not able. 
Removed linters and did it again but still, it runs twice

2020-10-13 09:14 UTC, merged